version: "3.9"

services:
  web:
    image: vergissberlin/talk-docker:latest
    build: .
    ports:
      - "8080:80"
    depends_on:
      - db
      - redis
    networks:
      - talk-docker
  db:
    image: postgres:latest
    environment:
      POSTGRES_PASSWORD: password
    networks:
        - talk-docker
  redis:
    image: redis:latest
    networks:
        - talk-docker

networks:
  default:
    external:
      name: talk-docker
